services:
  broker:
    image: rabbitmq:3-management
    ports:
      - 5672:5672  
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  
  jaeger:
    image: jaegertracing/all-in-one:1.60
    ports:
      - 16686:16686 # jaeger-ui
      - 6831:6831 # jaeger-agent-udp traces
      - 14268:14268 # jaeger-collector traces http
      - 4317:4317 # jaeger-collector traces otlp/grpc
      - 4318:4318 # jaeger-collector traces otlp/http
  

volumes:
  rabbitmq_data:
    driver: local