services:
  db:
    image: bitnami/postgresql:15
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: invoices
    ports:
      - 5433:5432
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
    
